WHILE(1 = 1)
	BEGIN
		
		DECLARE @OB_NAME NVARCHAR(128) = OBJECT_NAME((SELECT TOP 1 object_id FROM SYS.STATS WHERE user_created = 1))
		DECLARE @STAT_NAME NVARCHAR(128) = (SELECT TOP 1 name FROM SYS.STATS WHERE user_created = 1)
		DECLARE @SCHEMA_NAME NVARCHAR(128) = SCHEMA_NAME((SELECT schema_id FROM sys.objects WHERE name = @OB_NAME))
		
		DECLARE @SQL VARCHAR(1000) = 'DROP STATISTICS '+ @SCHEMA_NAME + '.' + @OB_NAME + '.' + @STAT_NAME
		EXEC(@SQL);
		--Terminating condition
		IF @SQL IS NULL BREAK
	END
GO
